# Generated by Django 4.2.7 on 2026-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_options_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name_lower',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
